app:
  name: Titan
  env: dev            # dev | prod
  debug: true

scheduler:
  interval_sec: 10    # 메인 루프 주기 (초)

trading:
  enabled: false
  buy_threshold_pct: 20.0
  max_positions: 3

log:
  level: INFO
  file: titan.log

kis:
  app_key: "PS840fN9DL1xLbIjwY5mmRadtLNxzA6lZ8WD"
  app_secret: "vCxAZIdRo8NOS1iiPrGSzViJ4NyZWb8EjkcJufZIsS2Z9vshgCB7tbWPE6OvhewED5tE9EkaLaTblm7cyRGQDWoGGtCtTaiLsN41ktuqshLcAdzdA6PE4yBMu241IJnZlqM1AknUIiJrbR3rNPkibHnsQc1Wvkr6BW4Py7HJoMDQTh33riU="
  base_url: "https://openapi.koreainvestment.com:9443"
  # base_url: "https://openapivts.koreainvestment.com:29443"

# # config.py
# KIS_APP_KEY = "PS840fN9DL1xLbIjwY5mmRadtLNxzA6lZ8WD"
# KIS_APP_SECRET = "vCxAZIdRo8NOS1iiPrGSzViJ4NyZWb8EjkcJufZIsS2Z9vshgCB7tbWPE6OvhewED5tE9EkaLaTblm7cyRGQDWoGGtCtTaiLsN41ktuqshLcAdzdA6PE4yBMu241IJnZlqM1AknUIiJrbR3rNPkibHnsQc1Wvkr6BW4Py7HJoMDQTh33riU="
# CANO = "..."
# ACNT_PRDT_CD = "01"
# KIS_API_BASE_URL = "https://openapi.koreainvestment.com:9443"
